spring.application.name=backend

server.port=8080

#  PostgreSQL connection personal
 spring.datasource.url=jdbc:postgresql://localhost:5432/cutsizer
 spring.datasource.username=postgres
 spring.datasource.password=vijay@30


# # # PostgreSQL connection ashdip

# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://168.231.120.70:5432/winsizer_cutsizer
# spring.datasource.username=postgres
# spring.datasource.password=qGe]Ax+$nbbQe6qf





# # Render server port
# server.port=${PORT:8080}

# # PostgreSQL on Render
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.cutsizer=DEBUG
logging.level.org.springframework.security=DEBUG

# JWT Configuration
jwt.secret=cutsizer-secret-key-change-this-in-production-must-be-at-least-256-bits-long-for-security
jwt.expiration=604800000

# TEST MODE (Use these for testing)
razorpay.key.id=rzp_test_RlsdeJP7YBOLHZ
razorpay.key.secret=5830aLOrxt9knpE7qOaRHavy